# Generated by Django 4.2.7 on 2025-08-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pricingplan_userprofile_pricing_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
