# Generated by Django 4.2.7 on 2025-08-22 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('center_lat', models.FloatField()),
                ('center_lng', models.FloatField()),
                ('grid_size', models.PositiveIntegerField(default=3)),
                ('radius_km', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RankingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataforseo_task_id', models.CharField(max_length=128, unique=True)),
                ('coord_lat', models.FloatField()),
                ('coord_lng', models.FloatField()),
                ('coord_zoom', models.PositiveIntegerField(default=15)),
                ('status', models.CharField(default='pending', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('target_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_position', models.PositiveIntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ranking_service.rankingjob')),
            ],
        ),
    ]
